"""empty message

Revision ID: 9c89305219d0
Revises: 
Create Date: 2019-11-21 09:51:18.145990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c89305219d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=True),
    sa.Column('send_time', sa.INTEGER(), nullable=True),
    sa.Column('discription', sa.TEXT(), nullable=True),
    sa.Column('shop_order_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
